USE [RestApi]

GO

DROP TABLE IF EXISTS [UsersRoles]

GO

CREATE TABLE [UsersRoles] (
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[RoleId] UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [PK_UsersRoles] PRIMARY KEY ([UserId], [RoleId]),
	CONSTRAINT [FK_UsersRoles_UserId] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_UsersRoles_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [Roles]([Id]) ON DELETE CASCADE,
)

GO